### ISSUE TITLE
Port interactions.py to 5.0.1

### ISSUE THREAD

**Issue by rechen-werk** [rechenwerk-a/Kilian#34]
**Is your feature request related to a problem? Please describe.**
Currently the bot is using version 4.4.0, which contains the bug that the bot gets stuck when loosing internet connection.
See: https://github.com/interactions-py/interactions.py/issues/979

**Describe the solution you'd like**
A comment there says porting to interactions.py 5.0.1 should fix the problem.

**Comment by BioGustav** [comment]
Porting won't be done, cronjob or something like it will be enough..
